---
# vars file for roles/conf-all
icons_url:
  - https://github.com/Nitrux/ardis-icon-theme/archive/refs/heads/master.zip
  - https://github.com/Nitrux/nitrux-icon-theme/archive/refs/heads/master.zip

icons_extract_zip:
  - /tmp/ardis-icon-theme-master.zip
  - /tmp/nitrux-icon-theme-master.zip

dir_temas:
  - mv /tmp/ardis-icon-theme-master /usr/share/icons/ardis-icons
  - mv /tmp/nitrux-icon-theme-master/Nitrux /usr/share/icons/nitrux-icons

font_ubuntu:
  - https://assets.ubuntu.com/v1/0cef8205-ubuntu-font-family-0.83.zip

fonts_extract_zip:
  - /tmp/0cef8205-ubuntu-font-family-0.83.zip

dir_fontes:
 - mv /tmp/ubuntu-font-family-0.83 /usr/share/fonts/

pictures_rul:
  - https://www.pexels.com/photo/97082/download/ #cachorro
  - https://www.pexels.com/photo/730896/download/ #gato
  - https://www.pexels.com/photo/39619/download/ #nascar-1
  - https://www.pexels.com/photo/40376/download/ #nascar-2
  - https://www.pexels.com/photo/289586/download/ #pedras
  - https://www.pexels.com/photo/4280481/download/ #cristoredentor-1
  - https://www.pexels.com/photo/5195468/download/ #cristoredentor-2
  - https://www.pexels.com/photo/7712570/download/ #bitcoin
  - https://www.pexels.com/photo/169573/download/ #codificacao-1
  - https://www.pexels.com/photo/97077/download/ #codificacao-2
  
copy_B:
  - mv /tmp/BEMOBI /tmp/BEMOBI_$(date +'%Y-%m-%d')
  - mv /tmp/BEMOBI* /home/glauber.fonseca/

conf_lightdm_gtk:
  - lightdm-gtk-greeter/lightdm-gtk-greeter.conf
  - lightdm-gtk-greeter/Gas-Soldier-with-Weapon-64x64.png
  - lightdm-gtk-greeter/TheMandalorian_BabyYoda_StarWars.jpeg
  