---
- hosts: local
  become: yes
  roles:
  - { role: add-repo, tags: add_repo }
  - { role: uninstall-app, tags: uninstall_app }
  - { role: install-app, tags: install_app }
  - { role: install-loffice, tags: install_loffice}
  - { role: create-user, tags: create_user}
  - { role: reboot-system, tags: reboot_system}
