---
# vars file for roles/create-user

new_user:
#  - glauber
#  - gabriel
#  - larissa

comment_user:
#  - Glauber GF
#  - Gabriel BF
#  - Larissa BF

#password:
#  - zaq1
#  - zaq1

delete_user:
#  - teste