---
# vars file for roles/aws-cli

# AWS Configure
aws_system_user: xxxxxxxxxx
aws_profile: default
access_key_id: XXXXXXXXXXXXXXXXXXXX
secret_access_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
aws_region: us-east-1
aws_format: json

# Adicionar linhas de configuração no .bashrc
bashrc:
  - echo '' >> /home/mcnd2/.bashrc
  #- echo '# AWSGO, ALOG e HISTORY_TIME' >> /home/mcnd2/.bashrc
  #- echo 'awsgo() { /usr/bin/ssh -i /home/mcnd2/.ssh/id_rsa_aws_glauber glauber@"$@";}' >> /home/mcnd2/.bashrc
  #- echo 'alog() { /usr/bin/ssh glauber.fonseca@10.5.9."$@";}' >> /home/mcnd2/.bashrc
  - echo 'HISTTIMEFORMAT="$USER %d/%m/%Y %T "' >> /home/mcnd2/.bashrc

# Copiar chave de acesso ssh
ssh_copy_id:
  - ssh-copy-id -i /home/mcnd2/.ssh/debiandesk_id_rsa mcnd2@192.168.0.103
