---
#----- Remove User
#- name: Removendo Conta(s) do(s) Usuario(s)
#  user:
#    name: "{{ item }}"
#    state: absent
#    remove: yes
#  with_items: "{{ delete_user }}"
#  tags: remove_user
#-----

- name: Criando Conta de Usuario(s)
  user:
    name: "{{ item.0 }}"
    uid: "{{ item.0.uid | default(omit, True) }}"
    groups: sudo
    comment: "{{ item.1 }}"
    password: "{{ 'zaq1' | string | password_hash('sha512') }}"
    create_home: yes
    state: present
    append: yes
    shell: "/bin/bash"
    update_password: on_create
  with_together:
    - "{{ new_user }}"
    - "{{ comment_user }}"
  register: user_created
  tags: create_user

- name: Forca o Usuario a Alterar a Senha no Primeiro Login
  shell: chage -d 0 "{{ item }}"
  with_items: "{{ new_user }}"
  tags: create_user
