---
#- name: Removendo pacotes Libreoffice existente
#  apt:
#    name: libreoffice*
#    state: absent
#    purge: yes
#    autoclean: yes
#    autoremove: yes
#  tags: remove_loffice

- name: Baixando o "LibreOffice 7.4.7". Aguarde ... 
  get_url:
    url: "{{ item }}"
    dest: "/tmp"
    mode: "0755"
  with_items: "{{ libreoffice_url }}"
  tags: install_loffice

- name: Descompactando Pacotes do "LibreOffice 7.4.7"
  unarchive:
    src: "{{ item }}"
    dest: "/tmp"
    mode: "0755"
    remote_src: yes
  with_items: "{{ lo_extract_gz }}"
  tags: install_loffice

- name: Criando Lista de Pacotes [.deb] do "LibreOffice 7.4.7"
  shell: "{{ item }}"
  with_items: "{{ create_list_deb_lo }}"
  tags: install_loffice

- name : Gerando Variavel da Lista de Pacotes do "LibreOffice 7.4.7"
  shell: cat /tmp/loffice-main-deb.txt
  register: list_deb_lo
  tags: install_loffice

- name: Listando os Pacotes do "LibreOffice 7.4.7" com DEBUG
  debug:
    msg: "{{ list_deb_lo }}"
  tags: install_loffice

- name: Instalando Pacotes [.deb] do "LibreOffice 7.4.7"
  apt:
    deb: "{{ item }}"
    force: yes
  with_items: "{{ list_deb_lo.stdout_lines }}"
  tags: install_loffice