---
- name: Backup do ".config/xfce4" do usuario
  shell: mv /home/mcnd2/.config/xfce4 /home/mcnd2/.config/xfce4_bkp_$(date +'%Y%m%d_%s')
  tags: conf_all

- name: Copiando template do Painel do xfce4
  #reiniciar o sistema para aplicar.
  copy:
    src: xfce4/
    dest: /home/mcnd2/.config/xfce4
    owner: mcnd2
    group: mcnd2
    mode: '0766'
  tags: conf_all

- name: Backup do "lightdm-gtk-greeter.conf" do sistema
  shell: mv /etc/lightdm/lightdm-gtk-greeter.conf /etc/lightdm/lightdm-gtk-greeter_bkp_$(date +'%Y%m%d_%s').conf
  tags: conf_all

- name: Copiando template do utilitario de configuracao de login LightDM GTK+ Greeter
  #reiniciar o sistema para aplicar.
  copy:
    src: "{{ item }}"
    dest: /etc/lightdm/
    owner: root
    group: root
    mode: '0644'
  loop: "{{ conf_lightdm_gtk }}"
  tags: conf_all

- name: Baixando os pacotes de temas de icones "Ardis" e "Nitrux"
  get_url:
    url: "{{ item }}"
    dest: "/tmp"
    mode: "0755"
  with_items: "{{ icons_url }}"
  tags: conf_all

- name: Descompactando os pacotes de temas de icones "Ardis" e "Nitrux"
  unarchive:
    src: "{{ item }}"
    dest: "/tmp"
    mode: "0755"
    remote_src: yes
  with_items: "{{ icons_extract_zip }}"
  tags: conf_all

- name: Copiando os diretorios de temas de icones para o "/usr/share/icons"
  shell: "{{ item }}"
  loop: "{{ dir_temas }}"
  tags: conf_all

- name: Baixando o pacote de "fontes Ubuntu"
  get_url:
    url: "{{ item }}"
    dest: "/tmp"
    mode: '0755'
  loop: "{{ font_ubuntu }}"
  tags: conf_all

- name: Descompactando o pacote de "fontes Ubuntu"
  unarchive:
    src: "{{ item }}"
    dest: "/tmp"
    mode: "0755"
    remote_src: yes
  with_items: "{{ fonts_extract_zip }}"
  tags: conf_all

- name: Copiando os diretorios de fontes Ubuntu para o "/usr/share/fonts"
  shell: "{{ item }}"
  loop: "{{ dir_fontes }}"
  tags: conf_all

- name: Criando diretorio "/home/$user/Imagens/wallpaper" se não existir
  file:
    path: "/home/mcnd2/Imagens/wallpaper"
    state: directory
    owner: mcnd2
    group: mcnd2
    mode: '0755'
  tags: conf_all

- name: Baixando "papel de parede Pexels"
  get_url:
    url: "{{ item }}"
    dest: "/home/mcnd2/Imagens/wallpaper"
    owner: mcnd2
    group: mcnd2
    mode: '0755'
  loop: "{{ pictures_rul }}"
  tags: conf_all

#- name: Copiando diretorio de DADOS
#  copy:
#    src: /media/backup/dados
#    dest: /tmp
#    owner: mcnd2
#    group: mcnd2
#    mode: '0755'
#  tags: conf_all

#- name: continuando ... 
#  shell: "{{ item }}"
#  loop: "{{ copy_B }}"
#  tags: conf_all

- name: Reiniciando o Sistema devido as mudanças de arquivos de configuracoes [xfce4-panel e lightdm]
  reboot: 
    connect_timeout: 5 
    reboot_timeout: 300 
    pre_reboot_delay: 0 
    post_reboot_delay: 30 
    test_command: uptime 
  tags: conf_all
  