---
- name: Removendo pacotes default que nao serao usados
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
    autoclean: yes
    autoremove: yes
  loop: "{{ uninstall_app }}"
  tags: uninstall_app
