---
# vars file for add-repo
apt_key_urls:
  - https://dl.google.com/linux/linux_signing_key.pub #GoogleChrome
  - https://packages.microsoft.com/keys/microsoft.asc #VSCode
  - https://keys.anydesk.com/repos/DEB-GPG-KEY #AnyDesk
  - https://packagecloud.io/AtomEditor/atom/gpgkey #Atom
  - https://download.spotify.com/debian/pubkey_0D811D58.gpg #Spotify
  - https://download.docker.com/linux/debian/gpg #Docker
  - https://apt.releases.hashicorp.com/gpg #Hashicorp
  - https://mega.nz/linux/MEGAsync/Debian_11/Release.key #Megasync
  - https://download.teamviewer.com/download/linux/signature/TeamViewer2017.asc #Teamviewer

id_gpg:
  - 2FAB19E7CCB7F415 #OpenFortiGUI
  - 93C4A3FD7BB9C367 #Ansible
  - 2F7F0DA5FD5B64B9 #Lutris

apt_repo_urls:
  - url: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main #GoogleChrome
    filename: google-chrome
  - url: deb [arch=amd64,arm64,armhf] http://packages.microsoft.com/repos/code stable main #VSCode
    filename: vscode
  - url: deb http://deb.anydesk.com/ all main #Anydesk
    filename: anydesk
  - url: deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main #Atom
    filename: atom
  - url: deb http://repository.spotify.com stable non-free #Spotify
    filename: spotify
  - url: deb https://apt.iteas.at/iteas bullseye main #OpenFortiGUI
    filename: openfortigui
  - url: deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable #Docker
    filename: docker
  - url: deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main #Ansible
    filename: ansible
  - url: deb http://download.opensuse.org/repositories/home:/strycore/Debian_11 ./ #Lutris
    filename: lutris
  ## Repository to Hashicorp: consul/nomad/packer/terraform/vagrant/vault/waypoint
  ## Ao habilitar esse repositório será instalado a versão mais recente
  ## no sistema. Caso tenha VM criada com a versão estável do Debian 
  ## o provider não será gerenciado pelo Vagrant.
  ## Ainda não suporta a versão Bullseye.
  #- url: deb [arch=amd64] https://apt.releases.hashicorp.com bullseye main #Hashicorp
  #  filename: hashicorp
  - url: deb https://mega.nz/linux/MEGAsync/Debian_11/ ./ #Megasync
    filename: megasync
  - url: deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main #Microsoft Teams
    filename: ms-teams
  - url: deb https://linux.teamviewer.com/deb stable main #Teamviewer
    filename: teamviewer